#!/usr/bin/env bash
# generate-skill-registry.sh
#
# Scans skills/*/SKILL.md, extracts frontmatter (name, description),
# and writes orchestration/skill-registry.yaml.
#
# Run from repo root:
#   bash scripts/generate-skill-registry.sh
#
# This script is idempotent — safe to run repeatedly.
# The generated registry is committed to the repo so the front door
# agent can read it without runtime file scanning.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"
REGISTRY_FILE="$REPO_ROOT/orchestration/skill-registry.yaml"

# Ensure output directory exists
mkdir -p "$(dirname "$REGISTRY_FILE")"

# Header
cat > "$REGISTRY_FILE" << 'HEADER'
# Auto-generated by scripts/generate-skill-registry.sh
# Do not edit manually — re-run the script after adding or modifying skills.
#
# The front door agent reads this file to discover available skills.
# Each entry is extracted from the SKILL.md frontmatter in skills/<name>/.

generated_at: "TIMESTAMP"
skills:
HEADER

# Replace timestamp
if command -v gdate &> /dev/null; then
  TIMESTAMP=$(gdate -u +"%Y-%m-%dT%H:%M:%SZ")
elif date -u +"%Y-%m-%dT%H:%M:%SZ" &> /dev/null 2>&1; then
  TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
else
  TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%SZ")
fi
sed -i.bak "s/TIMESTAMP/$TIMESTAMP/" "$REGISTRY_FILE" && rm -f "$REGISTRY_FILE.bak"

# Track whether we found any skills
SKILL_COUNT=0

# Scan each skill directory
for skill_dir in "$SKILLS_DIR"/*/; do
  skill_md="$skill_dir/SKILL.md"

  # Skip if no SKILL.md
  if [ ! -f "$skill_md" ]; then
    echo "WARNING: $skill_dir has no SKILL.md — skipping" >&2
    continue
  fi

  # Extract frontmatter (between first pair of --- lines)
  in_frontmatter=false
  name=""
  description=""

  while IFS= read -r line; do
    if [ "$line" = "---" ]; then
      if [ "$in_frontmatter" = true ]; then
        break  # End of frontmatter
      else
        in_frontmatter=true
        continue
      fi
    fi

    if [ "$in_frontmatter" = true ]; then
      # Extract name field
      if [[ "$line" =~ ^name:\ *(.*) ]]; then
        name="${BASH_REMATCH[1]}"
      fi
      # Extract description field
      if [[ "$line" =~ ^description:\ *(.*) ]]; then
        description="${BASH_REMATCH[1]}"
      fi
    fi
  done < "$skill_md"

  # Validate required fields
  if [ -z "$name" ]; then
    echo "WARNING: $skill_md missing 'name' in frontmatter — skipping" >&2
    continue
  fi

  if [ -z "$description" ]; then
    echo "WARNING: $skill_md missing 'description' in frontmatter — skipping" >&2
    continue
  fi

  # Derive paths from directory structure
  skill_basename="$(basename "$skill_dir")"
  skill_path="skills/$skill_basename/SKILL.md"
  input_schema="skills/$skill_basename/schemas/input.schema.json"
  output_schema="skills/$skill_basename/schemas/output.schema.json"

  # Write entry
  cat >> "$REGISTRY_FILE" << EOF
  - name: "$name"
    description: "$description"
    path: "$skill_path"
    input_schema: "$input_schema"
    output_schema: "$output_schema"
EOF

  SKILL_COUNT=$((SKILL_COUNT + 1))
done

echo "Skill registry generated: $REGISTRY_FILE ($SKILL_COUNT skill(s))"
